---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dna
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dna-deployment
        version: v1
    spec:
      containers:
        - name: dna
          image: whitesoft/dna_api
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - MONGODB_URL: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: dna-service
spec:
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 32000
      name: http
  type: NodePort
  selector:
    name: dna-deployment